[project]
name = "workshop"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.1",
    "transformers==5.7.0",
    "torch==2.9.0",
    "jupyterlab>=4.6.3,<5",
    "umap-learn>=0.5.12",
    "matplotlib>=3.11.1",
    "plotly>=6.9.0",
    "pandas>=3.0.5",
    "scipy>=1.18.0",
    "scikit-learn>=1.9.0",
    "datasets>=5.0.1",
    "pacmap>=0.9.1",
    "captum",

]

[dependency-groups]
dev = [
    "pillow>=12.3.0",
    "ipywidgets"
]
